const PARAGRAPHS = {
  easy: [
    "The sun rises every morning and sets every evening. Birds sing sweet songs in the trees. Children play in the park after school. The world is full of beautiful things if you take the time to look around you.",
    "A good book can take you on an adventure without leaving your chair. Reading every day helps your mind grow stronger and smarter. Try to read something new and interesting each week to expand your knowledge.",
    "Dogs are known as man's best friend for a good reason. They are loyal, loving, and always happy to see you. A dog will never judge you and will always be by your side no matter what happens.",
    "Learning to cook is one of the most useful skills you can have. Making your own food saves money and lets you eat healthier meals. Start with simple recipes and work your way up to more complex dishes.",
    "Exercise is important for a healthy body and a happy mind. Even a short walk each day can make a big difference in how you feel. Try to move your body for at least thirty minutes every single day.",
    "Music has the power to change your mood in an instant. A happy song can lift your spirits when you are feeling sad. Playing an instrument is a great hobby that brings joy to both you and others around you.",
    "Water covers more than two thirds of the surface of our planet. The oceans are home to millions of different species of plants and animals. We must protect our seas and rivers to keep the earth healthy for future generations.",
    "Traveling to new places opens your eyes to different ways of living. Every country has its own unique culture, food, and traditions. Meeting people from other parts of the world teaches you a great deal about life.",
  ],
  medium: [
    "The human brain is a remarkable organ, capable of processing vast amounts of information every single second. It controls everything from breathing and heartbeat to complex thought and emotional responses. Scientists are still discovering new things about how the brain works and adapts to different challenges and experiences throughout our lives.",
    "Technology has transformed the way people communicate, work, and live their daily lives. The internet connects billions of people across the globe, making information available at the touch of a button. While these advances bring many benefits, they also create new challenges around privacy, security, and the digital divide between communities.",
    "Climate change represents one of the most pressing challenges facing humanity in the twenty-first century. Rising temperatures, melting ice caps, and extreme weather events are already affecting communities around the world. Addressing this crisis requires cooperation between governments, businesses, and individuals to reduce carbon emissions and transition to cleaner sources of energy.",
    "Photography is both a technical skill and an art form that requires patience and a keen eye for detail. Understanding light, composition, and timing are essential to capturing compelling images. Modern digital cameras and smartphones have made photography more accessible than ever, allowing people to document and share their unique perspective on the world.",
    "The relationship between sleep and cognitive performance is well established in scientific research. During sleep, the brain consolidates memories, processes emotions, and repairs itself at a cellular level. Adults who consistently get seven to nine hours of quality sleep perform better on tasks requiring attention, creativity, and decision-making compared to those who are sleep deprived.",
    "Entrepreneurship requires a unique combination of creativity, resilience, and strategic thinking. Building a successful business involves identifying a genuine problem, developing a viable solution, and convincing others to support your vision. Many of the world's most successful companies started as small ideas in someone's garage or dorm room before growing into global enterprises.",
    "The ancient practice of meditation has gained widespread popularity in recent decades as research reveals its many benefits. Regular meditation practice has been shown to reduce stress and anxiety, improve focus, and even change the structure of the brain. Just a few minutes of mindful breathing each day can have a significant positive impact on mental health.",
    "Urban planning plays a crucial role in shaping the quality of life for millions of people living in cities around the world. Well-designed public spaces, efficient transportation systems, and accessible green areas contribute to healthier and more connected communities. As urban populations continue to grow, planners face the challenge of building cities that are both sustainable and livable.",
  ],
  hard: [
    "Quantum mechanics fundamentally challenges our classical intuitions about the nature of reality, introducing concepts such as superposition, entanglement, and wave-particle duality that have no analogue in everyday experience. The probabilistic nature of quantum systems means that outcomes can only be predicted statistically, not deterministically, a feature that famously troubled Einstein, who believed that God does not play dice with the universe.",
    "The philosophical tradition known as existentialism emerged in the nineteenth and twentieth centuries as a response to the perceived inadequacy of rationalist and empiricist frameworks for understanding human existence. Thinkers such as Kierkegaard, Nietzsche, Sartre, and Heidegger argued that authentic selfhood requires confronting the fundamental absurdity and contingency of existence rather than retreating into comfortable illusions or prescribed social roles.",
    "Epigenetics has revolutionized our understanding of heredity by demonstrating that gene expression can be modified by environmental factors without altering the underlying DNA sequence. These modifications, which include methylation and histone acetylation, can persist across multiple generations, challenging the traditional neo-Darwinian synthesis and suggesting that acquired characteristics may play a more significant role in evolution than previously acknowledged.",
    "The emergence of large language models has prompted intense debate among researchers about the nature of intelligence and whether statistical pattern matching over vast corpora of text can give rise to genuine understanding. Critics argue that these systems are merely sophisticated autocomplete engines with no semantic grounding, while proponents contend that the boundary between syntactic manipulation and semantic comprehension may be less clear-cut than commonly assumed.",
    "Monetary policy transmission operates through several distinct channels, including interest rates, asset prices, exchange rates, credit availability, and expectations. Central banks adjust policy instruments to influence aggregate demand and inflation, but the efficacy of these interventions depends on the structural characteristics of the economy, the credibility of the institution, and the prevailing financial conditions in domestic and international markets.",
    "The Fermi paradox encapsulates the apparent contradiction between the high probability estimates for the existence of extraterrestrial civilizations, derived from arguments like the Drake equation, and the complete absence of any confirmed observational evidence for their existence. Proposed resolutions range from the sobering Great Filter hypothesis to suggestions that advanced civilizations deliberately avoid contact with less developed societies.",
    "Renaissance humanism represented a profound reorientation of European intellectual culture away from the medieval preoccupation with theological abstraction and toward a renewed engagement with classical antiquity, rhetoric, history, and the moral philosophy of ancient Greece and Rome. This transformation in educational ideals and scholarly method provided the intellectual foundation for subsequent developments in science, art, political theory, and religious reform.",
    "Neuroplasticity refers to the brain's remarkable ability to reorganize its synaptic connections in response to experience, learning, injury, or environmental changes throughout the entire lifespan of an organism. This capacity challenges earlier assumptions that the adult brain is essentially fixed in its architecture and opens promising therapeutic avenues for rehabilitation following stroke, traumatic brain injury, and neurodegenerative conditions.",
  ],
  quotes: [
    "The only way to do great work is to love what you do. If you have not found it yet, keep looking. Do not settle. As with all matters of the heart, you will know when you find it. Stay hungry, stay foolish, and never stop pursuing what sets your soul on fire.",
    "It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change. In the long run, adaptability and the willingness to evolve are the most powerful traits any organism or organization can possess in a rapidly shifting world.",
    "Twenty years from now you will be more disappointed by the things that you did not do than by the ones you did. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover your own extraordinary path.",
    "Success is not final, failure is not fatal. It is the courage to continue that counts. Every setback is a setup for a comeback, and every obstacle is an invitation to innovate. The measure of a person is not where they stand in moments of comfort but where they stand in times of challenge.",
    "The future belongs to those who believe in the beauty of their dreams. Do not be pushed around by the fears in your mind. Be led by the dreams in your heart. Courage is not the absence of fear but the decision that something else is more important than that fear.",
    "Happiness is not something ready-made. It comes from your own actions. You have the power to shape your experience of the world through the choices you make each day. Choose kindness, choose curiosity, choose growth, and you will find that happiness follows naturally in the wake of a life well lived.",
  ],
  code: [
    "const fetchData = async (url) => { try { const response = await fetch(url); if (!response.ok) throw new Error('Network response was not ok'); const data = await response.json(); return data; } catch (error) { console.error('Fetch error:', error); throw error; } };",
    "function debounce(func, wait) { let timeout; return function executedFunction(...args) { const later = () => { clearTimeout(timeout); func(...args); }; clearTimeout(timeout); timeout = setTimeout(later, wait); }; }",
    "const mergeSort = (arr) => { if (arr.length <= 1) return arr; const mid = Math.floor(arr.length / 2); const left = mergeSort(arr.slice(0, mid)); const right = mergeSort(arr.slice(mid)); return merge(left, right); };",
    "class EventEmitter { constructor() { this.events = {}; } on(event, listener) { if (!this.events[event]) this.events[event] = []; this.events[event].push(listener); return this; } emit(event, ...args) { if (this.events[event]) this.events[event].forEach(listener => listener(...args)); } }",
  ]
};

const getAllParagraphs = () => {
  return [...PARAGRAPHS.easy, ...PARAGRAPHS.medium, ...PARAGRAPHS.hard, ...PARAGRAPHS.quotes];
};

const getRandomParagraph = (difficulty = 'medium', exclude = '') => {
  const pool = PARAGRAPHS[difficulty] || PARAGRAPHS.medium;
  const filtered = pool.filter(p => p !== exclude);
  return filtered[Math.floor(Math.random() * filtered.length)];
};
